# Generated by Django 6.0 on 2026-03-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequemodel',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Deposited', 'Deposited'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
        migrations.CreateModel(
            name='DepositModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('deposit_slip', models.ImageField(upload_to='deposit_slips/')),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('cheque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='core.chequemodel')),
            ],
        ),
    ]
